[workspace]
members = [
    "./near-test"
]

# This configuration is needed to reduce size of the compiled wasm file
[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
