[package]
name = "near-test"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
near-sdk-sim = "3.2.0"

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"

[features]
main_net = []
